// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6NausOnz4QJtxHxP53aH8aQP0nc5GF-M',
    appId: '1:992755003368:web:652cff12d2e75d5a9dbe5d',
    messagingSenderId: '992755003368',
    projectId: 'shattably-fae2a',
    authDomain: 'shattably-fae2a.firebaseapp.com',
    storageBucket: 'shattably-fae2a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOKIUZn_vQqGu79lxr7AAWXtZOreslXJ8',
    appId: '1:992755003368:android:f2a3ad270618aab99dbe5d',
    messagingSenderId: '992755003368',
    projectId: 'shattably-fae2a',
    storageBucket: 'shattably-fae2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ck7GNVFAnB0Ym1MgV9ZLPWV8U8qkV2U',
    appId: '1:992755003368:ios:ec766768156bbf1a9dbe5d',
    messagingSenderId: '992755003368',
    projectId: 'shattably-fae2a',
    storageBucket: 'shattably-fae2a.appspot.com',
    iosBundleId: 'com.example.shattably',
  );
}
